sudo: required
dist: xenial
language: node_js
node_js:
  - "10"
cache: npm

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - guozetang@gmail.com # 设置通知邮件
    on_success: change
    on_failure: always

install:
  - npm install -g gitbook-cli
  - gitbook install

script:
  - gitbook build

after_script:
  - chmod +x ./scripts/build.sh
  - ./scripts/build.sh

env:
  global:
    - REF=github.com/nsslabcuus/dochub.git
